### ISSUE TITLE
Regions

### ISSUE THREAD

**Issue by dkeller9** [BlueBrain/voxcell#13]
I noticed that if I try to pull out the somatosensory cortex layer 2 using the logic in the example it does not get everything

ids = rm.find('SS2', 'acronym', with_descendants=True)
np.count_nonzero(np.isin(brain_regions.raw, list(ids)))

The list of regions that it pulls out is (614454286 )is less than the true number of layer 2 regions, which should be:

{614454286,614454294,614454296,614454298,614454300,614454302,614454304,614454306}

This is more a consequence of how the json hierarchy file is organized rather than voxcell itself, but might be an indication that we need to rework the hierarchy file to accommodate such cases. I'm posting it here just so that we are aware of it.

**Comment by mgeplf** [comment]
I'm going to close this; we're also looking for a solution in https://bbpteam.epfl.ch/project/issues/browse/BBPP134-64
