### ISSUE TITLE
pynrrd1.0

### ISSUE THREAD

**Issue by arnaudon** [BlueBrain/voxcell#37]
with pynrrd1.1.1, its not needed to prepend None in https://github.com/BlueBrain/voxcell/blob/main/voxcell/voxel_data.py#L143

in fact, it results in a crash, so maybe we need to upper bound pynrrd in setup.py to <1?

**Comment by mgeplf** [comment]
We'll want this new version, as it removes the nptyping requirements.

However, yes, we need to fix this first.
If we don't prepend none, is the behavior correct?
Also, are the space dimensions being set right with the new version on read?
I don't think we want to change our API, so we'll need to work around that if they are different.

**Comment by mgeplf** [comment]
fixed in #38
